export interface Category {
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  productCount: number;
}

export const CATEGORIES: Category[] = [
  {
    slug: "ai-marketing-automation",
    name: "AI Marketing Automation",
    description: "AI-powered tools for cold outreach, email sequences, ad creative, and content generation.",
    icon: "🤖",
    color: "#6366f1",
    productCount: 20,
  },
  {
    slug: "email-marketing",
    name: "Email Marketing Platforms",
    description: "Full-featured email marketing platforms for newsletters, automation, and segmentation.",
    icon: "📧",
    color: "#f59e0b",
    productCount: 20,
  },
  {
    slug: "seo-content-tools",
    name: "SEO & Content Tools",
    description: "SEO research, rank tracking, content optimization, and technical audit tools.",
    icon: "🔍",
    color: "#10b981",
    productCount: 20,
  },
  {
    slug: "social-media-analytics",
    name: "Social Media & Analytics",
    description: "Social media scheduling, analytics, monitoring, and engagement tools.",
    icon: "📊",
    color: "#3b82f6",
    productCount: 20,
  },
  {
    slug: "crm-sales-automation",
    name: "CRM & Sales Automation",
    description: "Customer relationship management and sales pipeline automation platforms.",
    icon: "💼",
    color: "#ef4444",
    productCount: 20,
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

// All 100 products organized by category
export const ALL_PRODUCTS: Record<string, { slug: string; name: string; keyword: string }[]> = {
  "ai-marketing-automation": [
    { slug: "instantly-ai-review", name: "Instantly.ai", keyword: "instantly.ai review" },
    { slug: "smartlead-review", name: "Smartlead.ai", keyword: "smartlead review" },
    { slug: "lemlist-review", name: "Lemlist", keyword: "lemlist review" },
    { slug: "apollo-io-review", name: "Apollo.io", keyword: "apollo.io review" },
    { slug: "reply-io-review", name: "Reply.io", keyword: "reply.io review" },
    { slug: "woodpecker-review", name: "Woodpecker", keyword: "woodpecker email review" },
    { slug: "mailshake-review", name: "Mailshake", keyword: "mailshake review" },
    { slug: "jasper-review", name: "Jasper", keyword: "jasper ai review" },
    { slug: "copy-ai-review", name: "Copy.ai", keyword: "copy.ai review" },
    { slug: "writesonic-review", name: "Writesonic", keyword: "writesonic review" },
    { slug: "opus-clip-review", name: "Opus Clip", keyword: "opus clip review" },
    { slug: "descript-review", name: "Descript", keyword: "descript review" },
    { slug: "predis-ai-review", name: "Predis.ai", keyword: "predis.ai review" },
    { slug: "flick-review", name: "Flick", keyword: "flick social media review" },
    { slug: "taplio-review", name: "Taplio", keyword: "taplio review" },
    { slug: "adcreative-ai-review", name: "AdCreative.ai", keyword: "adcreative.ai review" },
    { slug: "pencil-ads-review", name: "Pencil", keyword: "pencil ads review" },
    { slug: "madgicx-review", name: "Madgicx", keyword: "madgicx review" },
    { slug: "motion-app-review", name: "Motion (ads)", keyword: "motion app review" },
    { slug: "foreplay-review", name: "Foreplay", keyword: "foreplay.co review" },
  ],
  "email-marketing": [
    { slug: "systeme-io-review", name: "Systeme.io", keyword: "systeme.io review" },
    { slug: "mailchimp-review", name: "Mailchimp", keyword: "mailchimp review" },
    { slug: "activecampaign-review", name: "ActiveCampaign", keyword: "activecampaign review" },
    { slug: "convertkit-review", name: "Kit (ConvertKit)", keyword: "convertkit review" },
    { slug: "klaviyo-review", name: "Klaviyo", keyword: "klaviyo review" },
    { slug: "drip-review", name: "Drip", keyword: "drip email marketing review" },
    { slug: "aweber-review", name: "AWeber", keyword: "aweber review" },
    { slug: "getresponse-review", name: "GetResponse", keyword: "getresponse review" },
    { slug: "brevo-review", name: "Brevo", keyword: "brevo review" },
    { slug: "omnisend-review", name: "Omnisend", keyword: "omnisend review" },
    { slug: "moosend-review", name: "Moosend", keyword: "moosend review" },
    { slug: "mailerlite-review", name: "MailerLite", keyword: "mailerlite review" },
    { slug: "campaign-monitor-review", name: "Campaign Monitor", keyword: "campaign monitor review" },
    { slug: "hubspot-email-review", name: "HubSpot Email", keyword: "hubspot email marketing review" },
    { slug: "constant-contact-review", name: "Constant Contact", keyword: "constant contact review" },
    { slug: "benchmark-email-review", name: "Benchmark Email", keyword: "benchmark email review" },
    { slug: "zoho-campaigns-review", name: "Zoho Campaigns", keyword: "zoho campaigns review" },
    { slug: "flodesk-review", name: "Flodesk", keyword: "flodesk review" },
    { slug: "sendgrid-review", name: "SendGrid", keyword: "sendgrid review" },
    { slug: "keap-review", name: "Keap", keyword: "keap review" },
    { slug: "iterable-review", name: "Iterable", keyword: "iterable review" },
  ],
  "seo-content-tools": [
    { slug: "ahrefs-review", name: "Ahrefs", keyword: "ahrefs review" },
    { slug: "semrush-review", name: "Semrush", keyword: "semrush review" },
    { slug: "surfer-seo-review", name: "Surfer SEO", keyword: "surfer seo review" },
    { slug: "frase-io-review", name: "Frase.io", keyword: "frase io review" },
    { slug: "clearscope-review", name: "Clearscope", keyword: "clearscope review" },
    { slug: "marketmuse-review", name: "MarketMuse", keyword: "marketmuse review" },
    { slug: "moz-pro-review", name: "Moz Pro", keyword: "moz pro review" },
    { slug: "screaming-frog-review", name: "Screaming Frog", keyword: "screaming frog review" },
    { slug: "mangools-review", name: "Mangools", keyword: "mangools review" },
    { slug: "ubersuggest-review", name: "Ubersuggest", keyword: "ubersuggest review" },
    { slug: "se-ranking-review", name: "SE Ranking", keyword: "se ranking review" },
    { slug: "rank-math-review", name: "Rank Math", keyword: "rank math review" },
    { slug: "yoast-seo-review", name: "Yoast SEO", keyword: "yoast seo review" },
    { slug: "majestic-seo-review", name: "Majestic", keyword: "majestic seo review" },
    { slug: "spyfu-review", name: "SpyFu", keyword: "spyfu review" },
    { slug: "brightlocal-review", name: "BrightLocal", keyword: "brightlocal review" },
    { slug: "nightwatch-seo-review", name: "Nightwatch", keyword: "nightwatch seo review" },
    { slug: "sitebulb-review", name: "Sitebulb", keyword: "sitebulb review" },
    { slug: "raven-tools-review", name: "Raven Tools", keyword: "raven tools review" },
    { slug: "conductor-seo-review", name: "Conductor", keyword: "conductor seo review" },
  ],
  "social-media-analytics": [
    { slug: "buffer-review", name: "Buffer", keyword: "buffer social media review" },
    { slug: "hootsuite-review", name: "Hootsuite", keyword: "hootsuite review" },
    { slug: "sprout-social-review", name: "Sprout Social", keyword: "sprout social review" },
    { slug: "metricool-review", name: "Metricool", keyword: "metricool review" },
    { slug: "later-app-review", name: "Later", keyword: "later app review" },
    { slug: "planoly-review", name: "Planoly", keyword: "planoly review" },
    { slug: "publer-review", name: "Publer", keyword: "publer review" },
    { slug: "socialbee-review", name: "SocialBee", keyword: "socialbee review" },
    { slug: "meetedgar-review", name: "MeetEdgar", keyword: "meetedgar review" },
    { slug: "sendible-review", name: "Sendible", keyword: "sendible review" },
    { slug: "iconosquare-review", name: "Iconosquare", keyword: "iconosquare review" },
    { slug: "brandwatch-review", name: "Brandwatch", keyword: "brandwatch review" },
    { slug: "mention-review", name: "Mention", keyword: "mention.com review" },
    { slug: "keyhole-review", name: "Keyhole", keyword: "keyhole review" },
    { slug: "emplifi-review", name: "Emplifi", keyword: "emplifi review" },
    { slug: "agorapulse-review", name: "Agorapulse", keyword: "agorapulse review" },
    { slug: "coschedule-review", name: "CoSchedule", keyword: "coschedule review" },
    { slug: "loomly-review", name: "Loomly", keyword: "loomly review" },
    { slug: "tailwind-app-review", name: "Tailwind", keyword: "tailwind app review" },
    { slug: "vista-social-review", name: "Vista Social", keyword: "vista social review" },
  ],
  "crm-sales-automation": [
    { slug: "hubspot-crm-review", name: "HubSpot CRM", keyword: "hubspot crm review" },
    { slug: "gohighlevel-review", name: "GoHighLevel", keyword: "gohighlevel review" },
    { slug: "pipedrive-review", name: "Pipedrive", keyword: "pipedrive review" },
    { slug: "close-crm-review", name: "Close.io", keyword: "close crm review" },
    { slug: "salesforce-review", name: "Salesforce", keyword: "salesforce review" },
    { slug: "monday-crm-review", name: "Monday.com CRM", keyword: "monday crm review" },
    { slug: "zoho-crm-review", name: "Zoho CRM", keyword: "zoho crm review" },
    { slug: "freshsales-review", name: "Freshsales", keyword: "freshsales review" },
    { slug: "copper-crm-review", name: "Copper CRM", keyword: "copper crm review" },
    { slug: "nimble-crm-review", name: "Nimble", keyword: "nimble crm review" },
    { slug: "keap-crm-review", name: "Keap CRM", keyword: "keap crm review" },
    { slug: "activecampaign-crm-review", name: "ActiveCampaign CRM", keyword: "activecampaign crm review" },
    { slug: "streak-crm-review", name: "Streak", keyword: "streak crm review" },
    { slug: "insightly-review", name: "Insightly", keyword: "insightly review" },
    { slug: "engagebay-review", name: "EngageBay", keyword: "engagebay review" },
    { slug: "nutshell-crm-review", name: "Nutshell", keyword: "nutshell crm review" },
    { slug: "less-annoying-crm-review", name: "Less Annoying CRM", keyword: "less annoying crm review" },
    { slug: "agile-crm-review", name: "Agile CRM", keyword: "agile crm review" },
    { slug: "salesmate-review", name: "Salesmate", keyword: "salesmate review" },
    { slug: "folk-crm-review", name: "Folk", keyword: "folk crm review" },
  ],
};
